#!/bin/bash

echo "POSTINST Script here called $0"

set -x

# Check for pm2, should we install it?
if [ ! -e /usr/local/bin/pm2 ]; then
        echo "PM2 not installed, should it be?"
fi

cd /opt/quadpbx/bin
/opt/quadpbx/bin/quadconf
/opt/quadpbx/bin/quadinstall

