#!/bin/bash

echo "quadpbx-og postinst script triggered"

cd /opt/quadpbx/bin
/opt/quadpbx/bin/quadconf

# If there is a '/.noinstall' file, don't install
if [ -e /.noinstall ]; then
        echo "/.noinstall file exists, not running quadinstall"
        echo "You can now run /opt/quadpbx/bin/quadinstall manually"
else
        echo "Running quadinstall - create the file /.noinstall to skip"
        /opt/quadpbx/bin/quadinstall
fi

